# Generated by Django 3.1.5 on 2021-01-20 22:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_number',
            field=models.CharField(default=users.models.random_code, max_length=10),
        ),
    ]
