# Generated by Django 3.1.5 on 2021-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter Date In The Format YYYY-MM-DD', null=True),
        ),
    ]
