# Generated by Django 3.1.5 on 2021-04-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_of_study', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(max_length=50)),
                ('state_or_city_1', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=1000)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('state_or_city_2', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('In A Relationship', 'In A Relationship'), ('Widow', 'Widow'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Remarried', 'Remarried')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('name_of_spouse', models.CharField(blank=True, max_length=30, null=True)),
                ('number_of_children', models.CharField(max_length=30)),
                ('children_age_bracket', models.CharField(max_length=20)),
                ('years_born_again', models.CharField(max_length=10)),
                ('salvation_experience', models.TextField()),
                ('spirit_baptism', models.BooleanField(default=False)),
                ('spiritual_gifts', models.CharField(max_length=100)),
                ('spiritual_fruit', models.CharField(max_length=100)),
                ('disability', models.BooleanField(default=False)),
                ('ministry_gift', models.CharField(max_length=20)),
                ('discplined', models.TextField()),
                ('ministry_experience', models.TextField()),
                ('spiritual_mentor', models.CharField(max_length=100)),
                ('obedience', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
