# Generated by Django 3.1.5 on 2021-04-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Chief', 'Chief')], default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='children_age_bracket',
            field=models.CharField(choices=[('0', '0'), ('1 - 5', '1 - 5'), ('6 - 10', '6 - 10'), ('11 - 20', '11 - 20'), ('Above 20', 'Above 20')], default=('0', '0'), max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
