# Generated by Django 3.1.5 on 2021-04-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_school', '0003_auto_20210414_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='application',
            name='children_age_bracket',
            field=models.CharField(choices=[('0', '0'), ('1 - 5', '1 - 5'), ('6 - 10', '6 - 10'), ('11 - 20', '11 - 20'), ('Above 20', 'Above 20')], default=('0', '0'), help_text='What is the age bracket of your children?', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='disability',
            field=models.BooleanField(default=False, help_text='Did you have any physical or emotional problem that might impair your studies in this institute?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='discplined',
            field=models.TextField(help_text='Have you ever been disciplined by your church for any act of immorality?  Give reasons if yes.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=('Male', 'Male'), help_text='Choose your gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('In A Relationship', 'In A Relationship'), ('Widow', 'Widow'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Remarried', 'Remarried')], default=('Single', 'Single'), help_text='What is your marital status?', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='ministry_experience',
            field=models.TextField(help_text='Share your ministerial experience/any post held'),
        ),
        migrations.AlterField(
            model_name='application',
            name='obedience',
            field=models.BooleanField(default=False, help_text='Are you ready to abide by the rules and regulation of S.B.I?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='spirit_baptism',
            field=models.BooleanField(default=False, help_text='Have you receive the baptism of Holy Spirit according to Acts 2:4?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Chief', 'Chief')], default=('Pastor', 'Pastor'), help_text='Choose a title from the options above', max_length=20),
        ),
    ]
