# Generated by Django 3.1.5 on 2021-11-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_school', '0004_auto_20210414_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Evangelist', 'Evangelist'), ('Deacon', 'Deacon'), ('Deaconess', 'Deaconess'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Chief', 'Chief')], default=('Pastor', 'Pastor'), help_text='Choose a title from the options above', max_length=20),
        ),
    ]
