# Generated by Django 3.1.5 on 2022-01-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_school', '0005_auto_20211105_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ministry_gift',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='place_of_birth',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='years_born_again',
            field=models.CharField(max_length=15),
        ),
    ]
