# Generated by Django 3.1.5 on 2021-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='award_image_1',
            field=models.ImageField(upload_to='awards_1/'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='award_image_2',
            field=models.ImageField(upload_to='awards_2/'),
        ),
    ]
